### ISSUE TITLE
Add 3DST previews in File Explorer on Windows (feature request)

### ISSUE THREAD

**Issue by ghost** [STBrian/MC3DS-Texture-Maker#7]
I think it would be nice if the 3DST viewer application would be able to present previews in the File Explorer, like this:
![image](https://github.com/user-attachments/assets/bdc96abf-4e6a-496e-b045-202ad368fac6)

**Comment by Cracko298** [comment]
Thats a Windows Feature for common formats.
You'd have to hack or get Microsoft to accept your low-level image stuff for it too work as such.

**Comment by STBrian** [comment]
I would need to do a lot of other things to achieve this. So it's not likely that I will do it.
