### ISSUE TITLE
Incorrect/swapped names in block texture list

### ISSUE THREAD

**Issue by SeveringHams** [STBrian/MC3DS-Texture-Maker#8]
The GUI name for the textures `grass_block_side_83b593` and `grass_block_side_88bb66` are swapped. 

This is confirmed by `#83b593` and `#88bb66` being in opposite places in `terrain_texture.json`, as compared to the names in your program.

Here are some visual examples:
This is me applying the color `#83b593` to an uncolored grass texture (on the left) beside the texture exported from `grass_block_side_83b593` (on the right):
![83b593](https://github.com/user-attachments/assets/5be53733-6ad7-419f-8dda-5585edff29d5)
Here is the same, but with the uncolored grass side texture colored with `#88bb66` beside the texture exported from `grass_block_side_83b593`:
![88bb66](https://github.com/user-attachments/assets/b24926ae-4037-4bf8-b8bf-5fa90c71d83a)
Here is the same but with `#64c73f` and it's corresponding grass texture export:
![64c73f](https://github.com/user-attachments/assets/2f5ab661-e6a9-4ceb-af8c-4159b3c2bc6f)

I absolutely love the program, and I hope you join us back on the MC3DS modding party server again!
Best wishes, 
SeveringHams

**Comment by Cracko298** [comment]
> The GUI name for the textures `grass_block_side_83b593` and `grass_block_side_88bb66` are swapped.
> 
> This is confirmed by `#83b593` and `#88bb66` being in opposite places compared to the your program in `terrain_texture.json`
> 
> Here are some visual examples: This is me applying the color `#83b593` to an uncolored grass texture (on the left) beside the texture exported from `grass_block_side_83b593` (on the right): ![83b593](https://private-user-images.githubusercontent.com/49352616/362968168-5be53733-6ad7-419f-8dda-5585edff29d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODY2ODYsIm5iZiI6MTcyNDk4NjM4NiwicGF0aCI6Ii80OTM1MjYxNi8zNjI5NjgxNjgtNWJlNTM3MzMtNmFkNy00MTlmLThkZGEtNTU4NWVkZmYyOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzk3YTYwMzRhODE3Mjg3NmJkNTEwOGFjZjU0NjI1ZjI5MDE4Y2Q3ZDJkNTVmZmZjNTAwOWIxMzc0NWZkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mA4jz1U2zHjGuVeGSXi6cbX0LAzCVuuxHDSAc-UIbNk) Here is the same, but with the uncolored grass side texture colored with `#88bb66` beside the texture exported from `grass_block_side_83b593`: ![image](https://private-user-images.githubusercontent.com/49352616/362969000-b24926ae-4037-4bf8-b8bf-5fa90c71d83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODY2ODYsIm5iZiI6MTcyNDk4NjM4NiwicGF0aCI6Ii80OTM1MjYxNi8zNjI5NjkwMDAtYjI0OTI2YWUtNDAzNy00YmY4LWI4YmYtNWZhOTBjNzFkODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDY5NjQzOTQzZWIyYTljNDI4MjAzNjdkY2Y2YWY1MDYzNDA3Y2ZkYjk5NGQ5NTE2ZjI2MThiZjhkNmVlNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MGvsHlb2zO7Yueb0h-iL4jy2dqPMGakd9QqML59mmik) Here is the same but with `#64c73f` and it's corresponding grass texture export: ![64c73f](https://private-user-images.githubusercontent.com/49352616/362968513-2f5ab661-e6a9-4ceb-af8c-4159b3c2bc6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODY2ODYsIm5iZiI6MTcyNDk4NjM4NiwicGF0aCI6Ii80OTM1MjYxNi8zNjI5Njg1MTMtMmY1YWI2NjEtZTZhOS00Y2ViLWFmOGMtNDE1OWIzYzJiYzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYmI5ODRmZjRhYmY4MGNjZDhlODg0MjA1MWU1NzAwMTRmNDE2YjRjMzk0YjY5ODg3MTczZjE5Yjg0Y2IwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AiaOK-Q9AoBxi5A7u2LgP_i2NHSmhOVeOreBQ3QD7Zo)
> 
> I absolutely love the program, and I hope you join us back on the MC3DS modding party server again! Best wishes, SeveringHams

Please check if the Windows build is also affected as well.

**Comment by SeveringHams** [comment]
> > The GUI name for the textures `grass_block_side_83b593` and `grass_block_side_88bb66` are swapped.
> > This is confirmed by `#83b593` and `#88bb66` being in opposite places compared to the your program in `terrain_texture.json`
> > Here are some visual examples: This is me applying the color `#83b593` to an uncolored grass texture (on the left) beside the texture exported from `grass_block_side_83b593` (on the right): ![83b593](https://private-user-images.githubusercontent.com/49352616/362968168-5be53733-6ad7-419f-8dda-5585edff29d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODY2ODYsIm5iZiI6MTcyNDk4NjM4NiwicGF0aCI6Ii80OTM1MjYxNi8zNjI5NjgxNjgtNWJlNTM3MzMtNmFkNy00MTlmLThkZGEtNTU4NWVkZmYyOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzk3YTYwMzRhODE3Mjg3NmJkNTEwOGFjZjU0NjI1ZjI5MDE4Y2Q3ZDJkNTVmZmZjNTAwOWIxMzc0NWZkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mA4jz1U2zHjGuVeGSXi6cbX0LAzCVuuxHDSAc-UIbNk) Here is the same, but with the uncolored grass side texture colored with `#88bb66` beside the texture exported from `grass_block_side_83b593`: ![image](https://private-user-images.githubusercontent.com/49352616/362969000-b24926ae-4037-4bf8-b8bf-5fa90c71d83a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODY2ODYsIm5iZiI6MTcyNDk4NjM4NiwicGF0aCI6Ii80OTM1MjYxNi8zNjI5NjkwMDAtYjI0OTI2YWUtNDAzNy00YmY4LWI4YmYtNWZhOTBjNzFkODNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMDY5NjQzOTQzZWIyYTljNDI4MjAzNjdkY2Y2YWY1MDYzNDA3Y2ZkYjk5NGQ5NTE2ZjI2MThiZjhkNmVlNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MGvsHlb2zO7Yueb0h-iL4jy2dqPMGakd9QqML59mmik) Here is the same but with `#64c73f` and it's corresponding grass texture export: ![64c73f](https://private-user-images.githubusercontent.com/49352616/362968513-2f5ab661-e6a9-4ceb-af8c-4159b3c2bc6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODY2ODYsIm5iZiI6MTcyNDk4NjM4NiwicGF0aCI6Ii80OTM1MjYxNi8zNjI5Njg1MTMtMmY1YWI2NjEtZTZhOS00Y2ViLWFmOGMtNDE1OWIzYzJiYzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAyNTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYmI5ODRmZjRhYmY4MGNjZDhlODg0MjA1MWU1NzAwMTRmNDE2YjRjMzk0YjY5ODg3MTczZjE5Yjg0Y2IwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AiaOK-Q9AoBxi5A7u2LgP_i2NHSmhOVeOreBQ3QD7Zo)
> > I absolutely love the program, and I hope you join us back on the MC3DS modding party server again! Best wishes, SeveringHams
> 
> Please check if the Windows build is also affected as well.

What do you mean?

**Comment by STBrian** [comment]
Thanks, I'll fix it soon!

**Comment by STBrian** [comment]
Thank you, the labels have been changed
