### ISSUE TITLE
Please add mipmapping support in the 3DST viewer

### ISSUE THREAD

**Issue by ghost** [STBrian/MC3DS-Texture-Maker#9]

**Comment by STBrian** [comment]
I can do it, but, you want to see the mipmaps? Or what would you use this function for? Since mipmaps are just the same texture but with half the resolution of the previous one, unless mipmaps doesn't match because only replaced full sized texture

**Comment by STBrian** [comment]
What I'm trying to say is, can you be more specific about what you want?

**Comment by STBrian** [comment]
Well, you didn't provide any description, but I've already added the option to show them anyway, will be located in the View tab
